### ISSUE TITLE
PC  пропущен?

### ISSUE THREAD

**Issue by citrusn** [FoxLib/Z80CAWinXPDev#1]
always @(negedge clock) 
if (reset_n == 1'b0) begin 

    af <= 16'hFFFF;
    sp <= 16'hFFFF;

end
Здесь не надо сбрасывать счетчик инструкций?

**Comment by FoxLib** [comment]
Тут все нормально. Это запись в регистры на негативном фронте. Вчера увидел в доке, добавил. Сброс на позитивном фронте счетчика находится в z80.v
