### ISSUE TITLE
Ula.v оптимизация

### ISSUE THREAD

**Issue by citrusn** [FoxLib/Z80CAWinXPDev#2]
Здесь можно сэкономить:
reg [23:0]  timer; - если считать кадры, то такой большой счетчик не понадобится
reg [18:0]  t50hz; - не используется

**Comment by FoxLib** [comment]
#1 
reg [18:0] t50hz; Я его на время убрал, потом верну

#2
reg [23:0]  timer;
Здесь тоже все правильно. 2^24 ~ 16 млн.

Ниже находится счетчик if (timer == 24'd12500000) циклов. Тактовая частота 25 мгц.

**Comment by citrusn** [comment]
#2 это видел, но чтобы получить частоту для мигания можно считать кадровые импульсы, они идут с гораздо меньшей частотой.

**Comment by FoxLib** [comment]
Понял, согласен, но я опираюсь на clock везде, не хочу приклеивать к сигналу VS.
